config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'omniauth_callbacks'
  }

  devise_scope :user do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
  end

  mount Shrine.upload_endpoint(:cache) => '/upload'
  resources :works do
    resources :versions, controller: :work_versions do # ,  shallow: true ???
      get 'file_list', to: 'file_lists#edit'
      put 'file_list', to: 'file_lists#update'
      patch 'file_list', to: 'file_lists#update'
      get 'publish', to: 'work_versions#publish'
      resources :files, controller: :file_version_memberships
    end
  end
  root 'works#index'
end

app/models/work_version.rb
# frozen_string_literal: true

class WorkVersion < ApplicationRecord
  include AASM

  aasm do
    state :draft, intial: true
    state :published, :withdrawn, :removed

    event :publish do
      transitions from: [:draft, :withdrawn], to: :published
    end

    event :withdraw do
      transitions from: :published, to: :withdrawn
    end

    event :remove do
      transitions from: [:draft, :withdrawn], to: :removed
    end
  end

  belongs_to :work, inverse_of: :versions
  has_many :file_version_memberships, dependent: :destroy
  has_many :file_resources, through: :file_version_memberships
  accepts_nested_attributes_for :file_resources

  jsonb_accessor :metadata,
                 title: :string,
                 subtitle: :string,
                 keywords: [:string, array: true, default: []],
                 rights: :string,
                 description: :string,
                 resource_type: :string,
                 contributor: :string,
                 publisher: :string,
                 published_date: :string,
                 subject: :string,
                 language: :string,
                 identifier: :string,
                 based_near: :string,
                 related_url: :string,
                 source: :string

  [:keywords].each do |array_field|
    define_method "#{array_field}=" do |vals|
      super(strip_blanks_from_array(vals))
    end
  end

  validates :title,
            presence: true

  validates :file_resources,
            presence: true,
            if: :published?

  validates :depositor_agreement,
            acceptance: true,
            if: :published?

  def display_version_name
    "Version: #{version_name.presence || version_index + 1}"
  end

  def version_index
    work.versions.order(created_at: :asc).to_enum.with_index.find { |version, _index| version == self }.last || 0
  end

  private

    def strip_blanks_from_array(arr)
      Array.wrap(arr).reject(&:blank?)
    end
end

app/controllers/work_versions_controller.rb
# frozen_string_literal: true

class WorkVersionsController < ApplicationController
  before_action :set_work_version, only: [:show, :edit, :update, :destroy]
  before_action :set_work

  def index; end

  def show; end

  def edit; end

  def publish
    @work_version = WorkVersion.find(params[:version_id])
  end

  def create
    # @todo scope to return latest published version
    # Additional logic: validate does a draft version currently exist?
    @work_version = BuildNewVersion.call(@work.versions.last)

    respond_to do |format|
      if @work_version.save
        format.html do
          redirect_to work_version_path(@work, @work_version), notice: 'Work version was successfully created.'
        end
        format.json { render :show, status: :created, location: @work_version }
      else
        format.html { render :new }
        format.json { render json: @work_version.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @work_version.attributes = work_version_params
      @work_version.publish if publish?
      if @work_version.save
        format.html do
          if publish?
            redirect_to work_path(@work), notice: 'Successfully published work!! Yey!'
          else
            redirect_to work_version_publish_path(@work, @work_version),
                        notice: 'Work version was successfully updated.'
          end
        end
        format.json { render :show, status: :ok, location: @work_version }
      else
        format.html do
          if publish?
            render :publish
          else
            render :edit
          end
        end
        format.json { render json: @work_version.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @work_version.destroy
    respond_to do |format|
      format.html { redirect_to versions_url, notice: 'Work version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_work_version
      @work_version = WorkVersion.find(params[:id])
    end

    def set_work
      @work = Work.find(params[:work_id])
    end

    def work_version_params
      params
        .require(:work_version)
        .permit(
          :title,
          :subtitle,
          { keywords: [] },
          :rights,
          :description,
          :resource_type,
          :contributor,
          :publisher,
          :published_date,
          :subject,
          :language,
          :identifier,
          :based_near,
          :related_url,
          :source,
          :depositor_agreement,
          :version_name
        )
    end

    def publish?
      params.key?(:publish)
    end
end

app/helpers/work_versions_helper.rb
# frozen_string_literal: true

module WorkVersionsHelper
end

app/views/work_versions/_form.html.erb
<% if work_version.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(work_version.errors.count, "error") %> prohibited this work_version from being saved:</h2>

    <ul>
    <% work_version.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form_fields', form: form %>

<div class="actions">
  <%= link_to "Back", work_version_file_list_path(@work, @work_version), class: 'btn btn-secondary' %>
  <%= form.submit "Save and Continue", class: 'btn btn-primary' %>
</div>

app/views/work_versions/_form_fields.html.erb
<div class="form-group">
  <%= form.label :title %>
  <%= form.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :version_name %>
  <%= form.text_field :version_name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :subtitle %>
  <%= form.text_field :subtitle, class: 'form-control' %>
</div>

<div class="form-group" data-controller="fields">
  <%= form.label :keywords %>
  <% form.object.keywords.push('').each do |keyword| %>
    <div class="input-group">
      <%= form.text_field :keywords, multiple: true, value: keyword, class: "form-control" %>
    </div>
  <% end %>
</div>

<div class="form-group">
  <%= form.label :rights %>
  <%= form.text_field :rights, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :description %>
  <%= form.text_area :description, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :resource_type %>
  <%= form.text_field :resource_type, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :contributor %>
  <%= form.text_field :contributor, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :publisher %>
  <%= form.text_field :publisher, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :published_date %>
  <%= form.text_field :published_date, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :subject %>
  <%= form.text_field :subject, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :language %>
  <%= form.text_field :language, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :identifier %>
  <%= form.text_field :identifier, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :based_near %>
  <%= form.text_field :based_near, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :related_url %>
  <%= form.text_field :related_url, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :source %>
  <%= form.text_field :source, class: 'form-control' %>
</div>

app/views/work_versions/_show_fields.html.erb
<h2><%= work_version.title %></h2>

<p>
  <strong>Version name:</strong>
  <%= work_version.version_name %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= work_version.subtitle %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= work_version.keywords.join(', ') %>
</p>

<p>
  <strong>Rights:</strong>
  <%= work_version.rights %>
</p>

<p>
  <strong>Description:</strong>
  <%= work_version.description %>
</p>

<p>
  <strong>Resource type:</strong>
  <%= work_version.resource_type %>
</p>

<p>
  <strong>Contributor:</strong>
  <%= work_version.contributor %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= work_version.publisher %>
</p>

<p>
  <strong>Published date:</strong>
  <%= work_version.published_date %>
</p>

<p>
  <strong>Subject:</strong>
  <%= work_version.subject %>
</p>

<p>
  <strong>Language:</strong>
  <%= work_version.language %>
</p>

<p>
  <strong>Identifier:</strong>
  <%= work_version.identifier %>
</p>

<p>
  <strong>Based near:</strong>
  <%= work_version.based_near %>
</p>

<p>
  <strong>Related url:</strong>
  <%= work_version.related_url %>
</p>

<p>
  <strong>Source:</strong>
  <%= work_version.source %>
</p>

app/views/work_versions/_show_files.html.erb
<% if work_version.file_resources.present? %>
  <table class="table table-striped">
    <thead>
      <tr><th>Name</th><th>Size</th><th>Mime Type</th></tr>
    </thead>
    <tbody>
      <% work_version.file_version_memberships.includes(:file_resource).each do |file| %>
      <tr>
        <td><%= file.title %></td>
        <td><%= number_to_human_size file.size %></td>
        <td><%= file.mime_type %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/work_versions/_work_version.html.erb
<%# NOTE, this file is probably going away, as it has been subsumed (maybe?) by
    works/_versions_sidebar, but we're not quite ready to commit yet. %>

<% is_active = active == work_version %>

<div class="card <%= 'border-primary' if is_active%>">
  <h5 class="card-header <%= 'border-primary' if is_active %>"><%= work_version.version_name || "Version #{work_version_iteration.index + 1}"  %></h5>
  <div class="card-body">
    <h5 class="card-title">
      <%= work_version.title %><span class="badge badge-primary"><%= work_version.aasm_state %></span>
    </h5>
    <p class="card-text"><%= work_version.description %></p>
    <%= link_to 'View', work_version_path(@work, work_version) %>
    <% if policy(work_version).edit? %>
      | <%= link_to 'Edit', edit_work_version_path(@work, work_version) %>
    <% end %>
  </div>
</div>

app/views/work_versions/edit.html.erb
<%# TODO extract this to a smart partial/helper/presenter %>
<div class="row">
  <div class="col">
    <ol class="progress-indicator">
      <li class="is-complete" data-step="1">Create</li>
      <li class="is-complete" data-step="2">Add Files</li>
      <li class="is-active" data-step="3">Add Metadata</li>
      <li data-step="4" class="progress__last">Publish</li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-sm-8">
    <%= form_with(model: @work_version, url: work_version_path(@work, @work_version), local: true) do |form| %>
      <%= render 'form', work_version: @work_version, form: form %>
    <% end %>
  </div>
</div>

app/views/work_versions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Versions</h1>

<%= render @work.versions %>

<%= link_to 'Back', work_path(@work) %> |
<%= link_to 'New Version', work_versions_path(@work), method: :post if policy(@work).create_version? %>

app/views/work_versions/new.html.erb
<h1>New Work Version</h1>

<%= form_with(model: @work_version, url: work_versions_path(@work), local: true) do |form| %>
  <%= render 'form', work_version: @work_version, form: form %>
<% end %>

<%= link_to 'Back', work_versions_path(@work) %>

app/views/work_versions/publish.html.erb
<%# TODO extract this to a smart partial/helper/presenter %>
<div class="row">
  <div class="col">
    <ol class="progress-indicator">
      <li class="is-complete" data-step="1">Create</li>
      <li class="is-complete" data-step="2">Add Files</li>
      <li class="is-complete" data-step="3">Add Metadata</li>
      <li class="is-active" data-step="4" class="progress__last">Publish</li>
    </ol>
  </div>
</div>


<div class="row">
  <div class="col-sm-8">
    <h1>Publishing Work Version</h1>

    <% if @work_version.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@work_version.errors.count, "error") %> prohibited this work_version from being saved:</h2>

        <ul>
          <% @work_version.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with(model: @work_version, url: work_version_path(@work, @work_version), local: true) do |form| %>

      <div class="form-group">
        <%= label_tag :access_level %>
        <div class="input-group">
          <%= select_tag :access_level,
            options_for_select(['Public', 'Penn State']),
            include_blank: false,
            class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :depositor_agreement %>
        <div class="form-check">
          <%= form.check_box :depositor_agreement,
            class: 'form-check-input' %>

          <%= form.label :depositor_agreement, "I agree to all the stuff I need to to make this work", class: 'form-check-label' %>
        </div>
      </div>

      <div class="actions">
        <%= link_to "Back", edit_work_version_path(@work, @work_version), class: 'btn btn-secondary' %>
        <%= form.button "Publish", name: "publish", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/work_versions/show.html.erb
<h1><%= @work_version.display_version_name %></h1>

<div class="row">
  <div class="col-sm-8">
    <%= work_version_badge @work.latest_version %>
    <%= render partial: 'show_fields', locals: { work_version: @work_version } %>
    <%= render partial: 'show_files', locals: { work_version: @work_version } %>
  </div>

  <div class="col-sm-4">
    <%= render 'works/versions_sidebar', work: @work, active: @work_version %>
  </div>
</div>