config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'omniauth_callbacks'
  }

  devise_scope :user do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
  end

  mount Shrine.upload_endpoint(:cache) => '/upload'
  resources :works do
    resources :versions, controller: :work_versions do # ,  shallow: true ???
      get 'file_list', to: 'file_lists#edit'
      put 'file_list', to: 'file_lists#update'
      patch 'file_list', to: 'file_lists#update'
      get 'publish', to: 'work_versions#publish'
      resources :files, controller: :file_version_memberships
    end
  end
  root 'works#index'
end

app/models/work.rb
# frozen_string_literal: true

class Work < ApplicationRecord
  belongs_to :depositor, class_name: 'User', foreign_key: 'depositor_id', inverse_of: 'works'
  has_many :work_creations, dependent: :restrict_with_exception
  has_many :aliases, through: :work_creations
  has_many :access_controls, as: :resource, dependent: :destroy
  has_many :versions, class_name: 'WorkVersion', inverse_of: 'work', dependent: :destroy

  accepts_nested_attributes_for :versions

  after_initialize :set_defaults

  module Types
    DATASET = 'dataset'

    def self.all
      [DATASET]
    end

    def self.display(type)
      type.humanize.titleize
    end

    def self.options_for_select_box
      all
        .sort
        .map { |type| [display(type), type] }
    end
  end

  validates :work_type,
            presence: true,
            inclusion: { in: Types.all }

  def latest_version
    versions.last
  end

  def latest_published_version
    versions.published.last
  end

  def draft_version
    versions.draft.last
  end

  private

    def set_defaults
      versions.build if versions.empty?
    end
end

app/controllers/works_controller.rb
# frozen_string_literal: true

class WorksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index; end

  # GET /works/1
  # GET /works/1.json
  def show; end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit; end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params.merge(depositor: current_user))

    respond_to do |format|
      if @work.save
        format.html do
          redirect_to work_version_file_list_path(@work, @work.versions.last),
                      notice: 'Work was successfully created.'
        end
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params
        .require(:work)
        .permit(
          :work_type,
          versions_attributes: [
            :title
          ]
        )
    end
end

app/helpers/works_helper.rb
# frozen_string_literal: true

module WorksHelper
  def work_version_badge(work_version, optional_class: '')
    klass = work_version.draft? ? 'badge-secondary' : 'badge-primary'
    title = work_version.aasm_state

    %(<span class="badge #{klass} #{optional_class}">#{title}</span>).html_safe
  end
end

app/views/works/_form.html.erb
<%= form_with(model: work, local: true) do |form| %>
  <% if work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.fields_for(:versions, work.versions.first) do |work_versions_form| %>
    <div class="form-group">
      <%= work_versions_form.label :title %>
      <div class="input-group">
        <%= work_versions_form.text_field :title, class: 'form-control' %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :work_type %>
    <div class="input-group">
      <%= form.select :work_type, Work::Types.options_for_select_box, {}, { class: 'form-control' } %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/works/_versions_sidebar.html.erb
<h2>Versions</h2>
<%= link_to('Create New Version', work_versions_path(work), method: :post, class: 'btn btn-primary') if policy(work).create_version? %>

<div class="versions-sidebar-list">
  <% work.versions.order(created_at: :desc).each_with_index do |work_version, index| %>
    <% is_active = active == work_version %>

    <div class="card <%= 'border-primary' if is_active%>">
      <h5 class="card-header <%= 'border-primary' if is_active %>">
        <%= work_version.display_version_name %>
        <%= work_version_badge work_version, optional_class: 'float-right' %>
      </h5>
      <div class="card-body">
        <h5 class="card-title">
          <%= work_version.title %>
        </h5>
        <p class="card-text"><%= work_version.description %></p>
        <%= link_to 'View', work_version_path(@work, work_version) %>
        <% if policy(work_version).edit? %>
          | <%= link_to 'Edit', work_version_file_list_path(@work, work_version) %>
        <% end %>
      </div>
    </div>

  <% end %>
</div>

app/views/works/_work.html.erb
<div class="card">
  <h5 class="card-header"><%= "Latest version: #{work.versions.count}" %></h5>
  <div class="card-body">
    <h5 class="card-title">
      <%= work.latest_version.title || "No Title" %>
      <span class="badge badge-primary"><%= work.latest_version.aasm_state %></span>
    </h5>
    <p class="card-text"><%= work.latest_version.description %></p>
    <%= link_to "Details", work %>
  </div>
</div>

app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Current Works</h1>

<%= render current_user.works %>

<%= link_to 'New Work', new_work_path %>

app/views/works/new.html.erb
<%# TODO extract this to a smart partial/helper/presenter %>
<div class="row">
  <div class="col">
    <ol class="progress-indicator">
      <li class="is-active" data-step="1">Create</li>
      <li data-step="2">Add Files</li>
      <li data-step="3">Add Metadata</li>
      <li data-step="4" class="progress__last">Publish</li>
    </ol>
  </div>
</div>


<div class="row">
  <div class="col-sm-8">
    <h1>Create A New Work</h1>
    <%= render 'form', work: @work %>

    <%= link_to 'Back', works_path %>
  </div>
</div>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Latest Version</h1>

<div class="row">
  <div class="col-sm-8">
    <%= work_version_badge @work.latest_version %>

    <%= render partial: 'work_versions/show_fields', locals: { work_version: @work.latest_version } %>
    <%= render partial: 'work_versions/show_files', locals: { work_version: @work.latest_version } %>
  </div>

  <div class="col-sm-4">
    <%= render 'versions_sidebar', work: @work, active: @work.versions.last %>
  </div>
</div>